
#define USART_MODBUS  USART1
#define NVIC_CONF_USART NVIC_USART1_IRQ
#define USART_CONF_ISR usart1_isr
#define RCC_CONF_USART RCC_USART1
#define DMA_CHANNEL_USART_WRITE DMA_CHANNEL4
#define DMA_CHANNEL_USART_WRITE_IRQ_HANDLER dma1_channel4_isr
#define NVIC_CONF_DMA_USART NVIC_DMA1_CHANNEL4_IRQ
#define USART_CONF_PORT (GPIOB)
#define USART_CONF_PINS (GPIO6 | GPIO7)

#define RS485DE_PORT GPIOB
#define RS485DE_PIN GPIO5
#define LED_TX_PORT GPIOB
#define LED_TX_PIN GPIO1
#define LED_RX_PORT LED_TX_PORT
#define LED_RX_PIN LED_TX_PIN